import { cacheLife, cacheTag } from "next/cache";

import type { HomePageData } from "@/types";

const homePageData = {
  heroSlides: [
    {
      id: "festival-earbuds",
      eyebrow: "Sale live now",
      title: "Earbud deals that move fast",
      description:
        "Curated TWS, neckbands and charging gear with quick filters by brand, category and price range.",
      offer: "Up to 55% off selected audio",
      ctaLabel: "Shop audio deals",
      href: "/products?category=earbuds",
      image: {
        src: "/assets/hero-carousel/hero-earbuds-sale.svg",
        alt: "Earbuds sale banner",
        width: 1120,
        height: 560,
        label: "hero-earbuds-sale.svg",
      },
    },
    {
      id: "smart-wearables",
      eyebrow: "Wearables week",
      title: "Smart watches under control",
      description:
        "Shop daily wear watches, fitness bands and accessories from trusted brands.",
      offer: "Starting from Rs. 899",
      ctaLabel: "Explore watches",
      href: "/products?category=smart-watch",
      image: {
        src: "/assets/hero-carousel/hero-smartwatch-sale.svg",
        alt: "Smart watch sale banner",
        width: 1120,
        height: 560,
        label: "hero-smartwatch-sale.svg",
      },
    },
    {
      id: "power-accessories",
      eyebrow: "Daily tech essentials",
      title: "Chargers, speakers and power banks",
      description:
        "Fast moving accessories organized for easy discovery across mobile and desktop.",
      offer: "New drops every week",
      ctaLabel: "Shop accessories",
      href: "/products?category=mobile-accessories",
      image: {
        src: "/assets/hero-carousel/hero-accessories-sale.svg",
        alt: "Accessories sale banner",
        width: 1120,
        height: 560,
        label: "hero-accessories-sale.svg",
      },
    },
    {
      id: "neckband-audio",
      eyebrow: "Neckband picks",
      title: "All-day audio that stays light",
      description:
        "Wireless neckbands for calls, commutes and workout playlists from daily-use brands.",
      offer: "Battery picks from Rs. 699",
      ctaLabel: "Shop neckbands",
      href: "/products?category=neckband",
      image: {
        src: "/assets/hero-carousel/hero-neckband-sale.svg",
        alt: "Neckband audio sale banner",
        width: 1120,
        height: 560,
        label: "hero-neckband-sale.svg",
      },
    },
    {
      id: "speaker-week",
      eyebrow: "Room-filling sound",
      title: "Bluetooth speakers for every desk",
      description:
        "Portable speakers, compact party audio and everyday sound bars organized by brand and price.",
      offer: "Speaker deals refreshed weekly",
      ctaLabel: "Shop speakers",
      href: "/products?category=speaker",
      image: {
        src: "/assets/hero-carousel/hero-speaker-sale.svg",
        alt: "Bluetooth speaker sale banner",
        width: 1120,
        height: 560,
        label: "hero-speaker-sale.svg",
      },
    },
    {
      id: "power-bank-week",
      eyebrow: "Charge anywhere",
      title: "Power banks and charging gear",
      description:
        "Fast chargers, cables and backup power options for travel, work and daily carry.",
      offer: "Charging gear from Rs. 499",
      ctaLabel: "Shop power gear",
      href: "/products?category=power-bank",
      image: {
        src: "/assets/hero-carousel/hero-powerbank-sale.svg",
        alt: "Power bank and charger sale banner",
        width: 1120,
        height: 560,
        label: "hero-powerbank-sale.svg",
      },
    },
  ],
  quickMenus: [
    { label: "Top deals", href: "/products?sort=deals", icon: "badge-percent" },
    { label: "New drops", href: "/products?sort=new", icon: "zap" },
    { label: "Earbuds", href: "/products?category=earbuds", icon: "headphones" },
    { label: "Watches", href: "/products?category=smart-watch", icon: "watch" },
    { label: "Fast delivery", href: "/products?delivery=fast", icon: "truck" },
    { label: "Warranty picks", href: "/products?warranty=true", icon: "shield" },
  ],
  brands: [
    {
      name: "OnePlus",
      slug: "oneplus",
      href: "/products?brand=oneplus",
      deal: "Premium audio",
      logo: {
        src: "/assets/brand-logos/oneplus-logo.svg",
        alt: "OnePlus logo",
        width: 220,
        height: 96,
        label: "oneplus-logo.svg",
      },
    },
    {
      name: "boAt",
      slug: "boat",
      href: "/products?brand=boat",
      deal: "Bass favorites",
      logo: {
        src: "/assets/brand-logos/boat-logo.svg",
        alt: "boAt logo",
        width: 220,
        height: 96,
        label: "boat-logo.svg",
      },
    },
    {
      name: "Redmi",
      slug: "redmi",
      href: "/products?brand=redmi",
      deal: "Value picks",
      logo: {
        src: "/assets/brand-logos/redmi-logo.svg",
        alt: "Redmi logo",
        width: 220,
        height: 96,
        label: "redmi-logo.svg",
      },
    },
    {
      name: "Realme",
      slug: "realme",
      href: "/products?brand=realme",
      deal: "Youth deals",
      logo: {
        src: "/assets/brand-logos/realme-logo.svg",
        alt: "Realme logo",
        width: 220,
        height: 96,
        label: "realme-logo.svg",
      },
    },
    {
      name: "Noise",
      slug: "noise",
      href: "/products?brand=noise",
      deal: "Watch and audio",
      logo: {
        src: "/assets/brand-logos/noise-logo.svg",
        alt: "Noise logo",
        width: 220,
        height: 96,
        label: "noise-logo.svg",
      },
    },
    {
      name: "PTron",
      slug: "ptron",
      href: "/products?brand=ptron",
      deal: "Budget audio",
      logo: {
        src: "/assets/brand-logos/ptron-logo.svg",
        alt: "PTron logo",
        width: 220,
        height: 96,
        label: "ptron-logo.svg",
      },
    },
    {
      name: "Ubon",
      slug: "ubon",
      href: "/products?brand=ubon",
      deal: "Accessories",
      logo: {
        src: "/assets/brand-logos/ubon-logo.svg",
        alt: "Ubon logo",
        width: 220,
        height: 96,
        label: "ubon-logo.svg",
      },
    },
    {
      name: "Go Boult",
      slug: "go-boult",
      href: "/products?brand=go-boult",
      deal: "Audio picks",
      logo: {
        src: "/assets/brand-logos/go-boult-logo.svg",
        alt: "Go Boult logo",
        width: 220,
        height: 96,
        label: "go-boult-logo.svg",
      },
    },
    {
      name: "Boult Audio",
      slug: "boult-audio",
      href: "/products?brand=boult-audio",
      deal: "TWS deals",
      logo: {
        src: "/assets/brand-logos/boult-audio-logo.svg",
        alt: "Boult Audio logo",
        width: 220,
        height: 96,
        label: "boult-audio-logo.svg",
      },
    },
    {
      name: "JBL",
      slug: "jbl",
      href: "/products?brand=jbl",
      deal: "Speakers",
      logo: {
        src: "/assets/brand-logos/jbl-logo.svg",
        alt: "JBL logo",
        width: 220,
        height: 96,
        label: "jbl-logo.svg",
      },
    },
    {
      name: "Zebronics",
      slug: "zebronics",
      href: "/products?brand=zebronics",
      deal: "Daily tech",
      logo: {
        src: "/assets/brand-logos/zebronics-logo.svg",
        alt: "Zebronics logo",
        width: 220,
        height: 96,
        label: "zebronics-logo.svg",
      },
    },
    {
      name: "Motorola",
      slug: "motorola",
      href: "/products?brand=motorola",
      deal: "Mobile gear",
      logo: {
        src: "/assets/brand-logos/motorola-logo.svg",
        alt: "Motorola logo",
        width: 220,
        height: 96,
        label: "motorola-logo.svg",
      },
    },
    {
      name: "Sony",
      slug: "sony",
      href: "/products?brand=sony",
      deal: "Audio quality",
      logo: {
        src: "/assets/brand-logos/sony-logo.svg",
        alt: "Sony logo",
        width: 220,
        height: 96,
        label: "sony-logo.svg",
      },
    },
    {
      name: "Ambrane",
      slug: "ambrane",
      href: "/products?brand=ambrane",
      deal: "Power deals",
      logo: {
        src: "/assets/brand-logos/ambrane-logo.svg",
        alt: "Ambrane logo",
        width: 220,
        height: 96,
        label: "ambrane-logo.svg",
      },
    },
    {
      name: "URBN",
      slug: "urbn",
      href: "/products?brand=urbn",
      deal: "Chargers",
      logo: {
        src: "/assets/brand-logos/urbn-logo.svg",
        alt: "URBN logo",
        width: 220,
        height: 96,
        label: "urbn-logo.svg",
      },
    },
    {
      name: "SYSKA",
      slug: "syska",
      href: "/products?brand=syska",
      deal: "Daily electronics",
      logo: {
        src: "/assets/brand-logos/syska-logo.svg",
        alt: "SYSKA logo",
        width: 220,
        height: 96,
        label: "syska-logo.svg",
      },
    },
    {
      name: "Philips",
      slug: "philips",
      href: "/products?brand=philips",
      deal: "Audio basics",
      logo: {
        src: "/assets/brand-logos/philips-logo.svg",
        alt: "Philips logo",
        width: 220,
        height: 96,
        label: "philips-logo.svg",
      },
    },
    {
      name: "Amazon Basics",
      slug: "amazon-basics",
      href: "/products?brand=amazon-basics",
      deal: "Essentials",
      logo: {
        src: "/assets/brand-logos/amazon-basics-logo.svg",
        alt: "Amazon Basics logo",
        width: 220,
        height: 96,
        label: "amazon-basics-logo.svg",
      },
    },
  ],
  categories: [
    {
      name: "True Wireless Earbuds",
      shortName: "Earbuds",
      slug: "earbuds",
      href: "/products?category=earbuds",
      description: "Compact TWS picks for calls, music and daily travel.",
      image: {
        src: "/assets/category-icons/earbuds.svg",
        alt: "Earbuds category",
        width: 320,
        height: 240,
        label: "earbuds.svg",
      },
    },
    {
      name: "Neckband",
      shortName: "Neckband",
      slug: "neckband",
      href: "/products?category=neckband",
      description: "Long battery audio for work and commute.",
      image: {
        src: "/assets/category-icons/neckband.svg",
        alt: "Neckband category",
        width: 320,
        height: 240,
        label: "neckband.svg",
      },
    },
    {
      name: "Power Bank",
      shortName: "Power Bank",
      slug: "power-bank",
      href: "/products?category=power-bank",
      description: "Backup charging for phones and accessories.",
      image: {
        src: "/assets/category-icons/power-bank.svg",
        alt: "Power bank category",
        width: 320,
        height: 240,
        label: "power-bank.svg",
      },
    },
    {
      name: "Smart Watch",
      shortName: "Watch",
      slug: "smart-watch",
      href: "/products?category=smart-watch",
      description: "Fitness, calls and daily notifications on wrist.",
      image: {
        src: "/assets/category-icons/smart-watch.svg",
        alt: "Smart watch category",
        width: 320,
        height: 240,
        label: "smart-watch.svg",
      },
    },
    {
      name: "Wireless Headphones",
      shortName: "Headphones",
      slug: "wireless-headphones",
      href: "/products?category=wireless-headphones",
      description: "Over-ear comfort with larger drivers.",
      image: {
        src: "/assets/category-icons/wireless-headphones.svg",
        alt: "Wireless headphones category",
        width: 320,
        height: 240,
        label: "wireless-headphones.svg",
      },
    },
    {
      name: "Wired Earphones",
      shortName: "Wired",
      slug: "wired-earphones",
      href: "/products?category=wired-earphones",
      description: "Reliable plug-in audio without battery concern.",
      image: {
        src: "/assets/category-icons/wired-earphones.svg",
        alt: "Wired earphones category",
        width: 320,
        height: 240,
        label: "wired-earphones.svg",
      },
    },
    {
      name: "Speaker",
      shortName: "Speaker",
      slug: "speaker",
      href: "/products?category=speaker",
      description: "Portable sound for rooms, travel and desks.",
      image: {
        src: "/assets/category-icons/speaker.svg",
        alt: "Speaker category",
        width: 320,
        height: 240,
        label: "speaker.svg",
      },
    },
    {
      name: "Laptop and Mobile Accessories",
      shortName: "Accessories",
      slug: "mobile-accessories",
      href: "/products?category=mobile-accessories",
      description: "Cables, adapters, stands and daily add-ons.",
      image: {
        src: "/assets/category-icons/mobile-accessories.svg",
        alt: "Mobile accessories category",
        width: 320,
        height: 240,
        label: "mobile-accessories.svg",
      },
    },
    {
      name: "Charging Accessories",
      shortName: "Charging",
      slug: "charging-accessories",
      href: "/products?category=charging-accessories",
      description: "Chargers and cables for fast top-ups.",
      image: {
        src: "/assets/category-icons/charging-accessories.svg",
        alt: "Charging accessories category",
        width: 320,
        height: 240,
        label: "charging-accessories.svg",
      },
    },
  ],
  collabSlides: [
    {
      id: "collab-oneplus",
      title: "OnePlus audio week",
      subtitle: "Branded product banner slot",
      href: "/products?brand=oneplus",
      image: {
        src: "/assets/collab-carousel/brand-banners/collab-oneplus-products.svg",
        alt: "OnePlus collaboration product banner",
        width: 1440,
        height: 620,
        label: "collab-oneplus-products.svg",
      },
    },
    {
      id: "collab-boat",
      title: "boAt bass collection",
      subtitle: "Auto/manual carousel image",
      href: "/products?brand=boat",
      image: {
        src: "/assets/collab-carousel/brand-banners/collab-boat-products.svg",
        alt: "boAt collaboration product banner",
        width: 1440,
        height: 620,
        label: "collab-boat-products.svg",
      },
    },
    {
      id: "collab-noise",
      title: "Noise watch and audio",
      subtitle: "Brand focused full-width graphic",
      href: "/products?brand=noise",
      image: {
        src: "/assets/collab-carousel/brand-banners/collab-noise-products.svg",
        alt: "Noise collaboration product banner",
        width: 1440,
        height: 620,
        label: "collab-noise-products.svg",
      },
    },
    {
      id: "collab-jbl",
      title: "JBL speaker spotlight",
      subtitle: "Product showcase banner",
      href: "/products?brand=jbl",
      image: {
        src: "/assets/collab-carousel/brand-banners/collab-jbl-products.svg",
        alt: "JBL collaboration product banner",
        width: 1440,
        height: 620,
        label: "collab-jbl-products.svg",
      },
    },
    {
      id: "redmi-realme",
      title: "Redmi and Realme value picks",
      subtitle: "Budget product banner slot",
      href: "/products?sort=deals",
      image: {
        src: "/assets/collab-carousel/brand-banners/collab-redmi-realme-products.svg",
        alt: "Redmi and Realme collaboration banner",
        width: 1440,
        height: 620,
        label: "collab-redmi-realme-products.svg",
      },
    },
    {
      id: "sony-premium",
      title: "Sony premium audio",
      subtitle: "Premium product banner slot",
      href: "/products?brand=sony",
      image: {
        src: "/assets/collab-carousel/brand-banners/collab-sony-products.svg",
        alt: "Sony collaboration banner",
        width: 1440,
        height: 620,
        label: "collab-sony-products.svg",
      },
    },
  ],
  warehouseSlides: [
    {
      id: "warehouse-rack",
      title: "Warehouse stock wall",
      subtitle: "Live stock and sorting area",
      href: "/about",
      image: {
        src: "/assets/collab-carousel/warehouse/warehouse-stock-wall.svg",
        alt: "Warehouse stock wall banner",
        width: 1440,
        height: 620,
        label: "warehouse-stock-wall.svg",
      },
    },
    {
      id: "packing-desk",
      title: "Packing and dispatch",
      subtitle: "Orders packed for quick handoff",
      href: "/shipping-policy",
      image: {
        src: "/assets/collab-carousel/warehouse/warehouse-packing-desk.svg",
        alt: "Warehouse packing desk banner",
        width: 1440,
        height: 620,
        label: "warehouse-packing-desk.svg",
      },
    },
    {
      id: "delivery-counter",
      title: "Fast delivery counter",
      subtitle: "Daily dispatch proof",
      href: "/products?delivery=fast",
      image: {
        src: "/assets/collab-carousel/warehouse/delivery-counter.svg",
        alt: "Fast delivery counter banner",
        width: 1440,
        height: 620,
        label: "delivery-counter.svg",
      },
    },
    {
      id: "accessories-wall",
      title: "Accessories wall",
      subtitle: "Accessories arranged by category",
      href: "/products?category=mobile-accessories",
      image: {
        src: "/assets/collab-carousel/warehouse/accessories-wall.svg",
        alt: "Accessories wall banner",
        width: 1440,
        height: 620,
        label: "accessories-wall.svg",
      },
    },
  ],
  trustItems: [
    {
      title: "Fast delivery",
      description: "Delivery filters and stock-aware browsing fit into the homepage flow.",
      metric: "24-72h",
    },
    {
      title: "Verified catalog",
      description: "Brand and category pages are prepared for fast product browsing.",
      metric: "Curated",
    },
    {
      title: "Support flow",
      description: "Footer and account entry points are ready for orders, warranty and returns.",
      metric: "7 days",
    },
  ],
  videoFeature: {
    title: "Product walkthrough",
    description:
      "A lightweight video slot for product reels, warehouse clips or launch footage without shifting the layout.",
    poster: {
      src: "/assets/content/product-video-cover.svg",
      alt: "Product video cover",
      width: 840,
      height: 472,
      label: "product-video-cover.svg",
    },
    video: {
      src: "/assets/content/our-product-video.mp4",
      type: "video/mp4",
      alt: "AllEarbuds product video",
    },
  },
} satisfies HomePageData;

export async function getHomePageData(): Promise<HomePageData> {
  "use cache";
  cacheLife("hours");
  cacheTag("home-page");

  return homePageData;
}
